export const clamp=(n,min=0,max=10)=>Math.min(max,Math.max(min,Number.isFinite(+n)?+n:0));
export const round=(n,d=2)=>Math.round((Number(n)||0)*10**d)/10**d;
export function parseGrade(value){if(value===null||value===undefined||String(value).trim()==='')return null;const n=Number(String(value).trim().replace(',','.'));return Number.isFinite(n)&&n>=0&&n<=10?n:null}
export function calculateAverage(grades=[]){const x=grades.map(parseGrade).filter(v=>v!==null);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null}
export function calculateWeightedAverage(items=[]){const x=items.map(i=>({grade:parseGrade(i.grade),weight:Number(i.weight)||0})).filter(i=>i.grade!==null&&i.weight>0);const w=x.reduce((a,b)=>a+b.weight,0);return w?x.reduce((a,b)=>a+b.grade*b.weight,0)/w:null}
export function termAverage(subject,term){let t=subject.terms?.[term-1];if(subject.calcMode==='manual'||subject.calcMode==='points'||t?.grade!=null)return t?.grade==null?null:parseGrade(t.grade);const a=(subject.assessments||[]).filter(x=>Number(x.term)===Number(term)).map(x=>({...x,grade:Number(x.maximumGrade)>0?Number(x.grade)*10/Number(x.maximumGrade):x.grade}));return subject.calcMode==='weighted'?calculateWeightedAverage(a):calculateAverage(a.map(x=>x.grade))}
export function calculateAnnualPoints(subject){return (subject.terms||[]).reduce((s,t,i)=>s+(termAverage(subject,i+1)??0),0)}
export function termsCompleted(subject){return (subject.terms||[]).filter((t,i)=>termAverage(subject,i+1)!==null).length}
export function calculateRequiredGrade(subject){const target=Number(subject.annualTarget??24),current=calculateAnnualPoints(subject),remaining=Math.max(0,Number(subject.termCount??4)-termsCompleted(subject));if(current>=target)return {needed:0,current,target,remaining,achievable:true,achieved:true};if(!remaining)return {needed:target-current,current,target,remaining:0,achievable:false,achieved:false};const needed=(target-current)/remaining;return {needed,current,target,remaining,achievable:needed<=10,achieved:false}}
export function calculateRemainingPoints(subject){return Math.max(0,Number(subject.annualTarget??24)-calculateAnnualPoints(subject))}
export function calculateStatus(subject){const r=calculateRequiredGrade(subject);if(r.achieved)return 'Aprovado';if(!r.achievable)return 'Impossível';const pct=r.current/(r.target||24);if(pct>=.8)return 'Bom';if(pct>=.65)return 'Atenção';return 'Risco'}
export function calculateProjectedAverage(subject,term,grade){const assess=(subject.assessments||[]).filter(a=>Number(a.term)===Number(term)).map(a=>({...a,grade:Number(a.maximumGrade)>0?Number(a.grade)*10/Number(a.maximumGrade):a.grade}));if(subject.calcMode==='manual'||subject.calcMode==='points')return round(parseGrade(grade)??0);if(subject.calcMode==='weighted'){const all=[...assess,{grade,weight:1}];return round(calculateWeightedAverage(all)??0)}return round(calculateAverage([...assess.map(a=>a.grade),grade])??0)}
export function calculateEvolution(subject){const grades=(subject.terms||[]).map((t,i)=>termAverage(subject,i+1));const completed=grades.filter(v=>v!==null);if(completed.length<2)return {direction:'→',change:0,grades};const change=completed.at(-1)-completed.at(-2);return {direction:change>0?'↑':change<0?'↓':'→',change:round(change,1),grades}}
export function calculateWorstCase(subject){return calculateRequiredGrade({...subject,terms:[...(subject.terms||[]).slice(0,-1),{grade:0}]})}
export function calculateBestCase(subject){return calculateRequiredGrade({...subject,terms:[...(subject.terms||[]).slice(0,-1),{grade:10}]})}
export function calculateScenario(subject,grade){let rem=Math.max(1,Number(subject.termCount??4)-termsCompleted(subject));return round(calculateAnnualPoints(subject)+Number(grade||0)+(rem-1)*5,1)}
